### ISSUE TITLE
Hi Edpanameno!

### ISSUE THREAD

**Issue by huuthangcnc** [edpanameno/ADWeb#43]
Can you tell me how this project work? I do not understand MVC and EF in ASP.NET. And can you share database (MSSQL) ?

**Comment by edpanameno** [comment]
Hi Huuthangcnc!

Sorry for the late reply.  The project is going to be used to connect to and manage active directory. The idea being that you can use it to create users and groups! Most of the features I am building are things that I do at work on a daily basis and I want to automate this a bit! The details on how this project works are in the source of the application available here in github.  As for understanding MVC and EF, those are really big topics and I myself am just learning how to use MVC so my advice for you is to just start building something with it (just like I am here). There are some really nice tutorials that you can find in google that can help you to get started!
